### ISSUE TITLE
can not work with golang in linux-i686

### ISSUE THREAD

**Issue by RyanCode** [ying32/liblcl#10]
```log
go build github.com/ying32/dylib: build constraints exclude all Go files in /root/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96
```

I build liblci in linux-i686

![image](https://user-images.githubusercontent.com/61410262/225201948-69da51b7-a65d-47b5-a661-3191605b658b.png)

**Comment by ying32** [comment]
The information you give is not of any reference value.

**Comment by RyanCode** [comment]
有一个很重要的问题，我使用64位linux的liblcl编译后，在其他不同内核平台、架构一样的机器上不能运行，会有许多的依赖冲突，请问liblcl是否可以静态编译？

**Comment by RyanCode** [comment]
而且在linux平台很容易崩溃
```log
Pango:ERROR:/build/buildd/pango1.0-1.30.0/./pango/pango-layout.c:3801:pango_layout_check_lines: assertion failed: (!layout->log_attrs)
SIGABRT: abort
PC=0x7f1dc5414445 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x8b4cf0, 0xc00010b880)
	/ryan/go/src/runtime/cgocall.go:157 +0x5c fp=0xc00010b858 sp=0xc00010b820 pc=0x40a91c
github.com/ying32/dylib._Cfunc_Syscall3(0x7f1d9b296e00, 0x7f1d9b296e80, 0x1, 0x7f1dc61478f0)
	_cgo_gotypes.go:195 +0x4d fp=0xc00010b880 sp=0xc00010b858 pc=0x79dc6d
github.com/ying32/dylib.(*LazyProc).CallOriginal.func4(0x79fee0?, {0xc00010b9b8?, 0xc000156f50?, 0xc00010b8d8?})
	/root/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:282 +0xe5 fp=0xc00010b8d8 sp=0xc00010b880 pc=0x7a1d85
github.com/ying32/dylib.(*LazyProc).CallOriginal(0xc000126c60, {0xc00010b9b8, 0x3, 0x3})
	/root/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:282 +0xd5 fp=0xc00010b950 sp=0xc00010b8d8 pc=0x7a0095
github.com/ying32/dylib.(*LazyDLL).call(0xc0000bcec0, 0xc000126db0, {0xc00010bd30?, 0x1, 0x1?})
	/root/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:199 +0x115 fp=0xc00010bd00 sp=0xc00010b950 pc=0x79f175
github.com/ying32/dylib.(*LazyProc).Call(...)
	/root/go/pkg/mod/github.com/ying32/dylib@v0.0.0-20220227124818-fdf9ea9fbc96/dylib_posix.go:264
github.com/ying32/govcl/vcl/api.Application_Run(0x7f1dc61478f0?)
	/root/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/api/applicationdef.go:28 +0x65 fp=0xc00010bd50 sp=0xc00010bd00 pc=0x7a2305
github.com/ying32/govcl/vcl.(*TApplication).Run(...)
	/root/go/pkg/mod/github.com/ying32/govcl@v2.2.0+incompatible/vcl/applicationdef.go:91
git.longersec.com/pgwagent/ui.Run()
	/ryan/pgw_agent/ui/run.go:19 +0x99 fp=0xc00010bd90 sp=0xc00010bd50 pc=0x8aa9f9
main.main()
	/ryan/pgw_agent/cmd/pgw_agent/main.go:105 +0x78a fp=0xc00010bf80 sp=0xc00010bd90 pc=0x8b352a

```

**Comment by ying32** [comment]
1、无法使用静态编译，有的话我早就提供了。linux版本太多，如果可能最好在自己需求的那个版本上重新编译liblcl，不过目前以ubuntu为基础的应该是没问题的。  
2、这种情况之前没听有反馈过，而且我也不知道你里面怎么写的。比如线程中操作ui没用文档中提到的方式就会容易崩溃，其他的暂未知。也可以自己编译dev分支的liblcl和使用dev分支的govcl看看。
